### ISSUE TITLE
TwitterCardの設定

### ISSUE THREAD

**Issue by raryosu** [NKMR6194/proconist.net#37]
:tada: 祝 ローンチ :tada: 

そこで気づいたのですが，TwitterCardの設定が完了していませんでした
>twitter:site

の設定が必須です。
https://dev.twitter.com/cards/types/summary-large-image

どのアカウントを利用するのでしょうか？

**Comment by NKMR6194** [comment]
`twitter:site` は実は設定しなくても通るみたいです。（ソースがあったのですが、忘れたので探してきます）
httpsだと通らず、httpだと表示出来るのでサーバー側の問題と思われます

**Comment by NKMR6194** [comment]
サーバーの設定をいろいろいじったて、むりやり修正しました。
一部コードの変更もしました 7c477162ebe5d4e9a75e9de303bff0e7d28463e9
