### ISSUE TITLE
ログインの挙動がおかしい

### ISSUE THREAD

**Issue by raryosu** [NKMR6194/proconist.net#39]
consoleからコンソール内の他ページに遷移する際、複数回ログインをうながされます。
たとえば、ユーザ設定にアクセスをこころみても、ログイン画面に遷移、ログイン後も再度ログイン画面に遷移します。
ログイン画面に遷移し、プロフィールを更新しようとすると再度ログイン画面に遷移、ログイン試行後、その変更は破棄されます。

(話はかわりますが、高専カンファレンス with プロコン(仮)のOB戦はソースコード公開が義務つけられているのでProconist.netでまとめていけばよさそうだとおもっています http://kosenconf.jp/?098procon )

**Comment by NKMR6194** [comment]
ごめんなさい。その問題はすでに認知していました。

セッション管理周りの認識が甘かったせいで、セキュリティ上の理由からに認証部分を作り直さないと行けない状態です。おいおい作り直しますが、直近でログインが必要そうですか？

**Comment by raryosu** [comment]
そうでしたか、すみません

特にいますぐログインが必要ということはありません（プロフィールを修正しようとしてただけなので）。
よろしくおねがいします。

**Comment by NKMR6194** [comment]
:bow:

**Comment by NKMR6194** [comment]
ログイン復活しました。お騒がせしました :joy:
