### ISSUE TITLE
Twitterボタンの表示変更に伴う修正

### ISSUE THREAD

**Issue by raryosu** [NKMR6194/proconist.net#40]
Twitterボタンの横に表示されていたツイート数表示が11月20日以降表示されなくなります。
( Source: https://blog.twitter.com/ja/2015/buttons )

これに伴う修正を今月中に行いたいと思っています。
その際，他のSNSボタンの吹き出し表示も無くした上で，SNSボタンを整列し直して現在と同じ位置に配置しようと考えています。
何か不都合があればご連絡ください。よろしくお願いします。（別ブランチで作業を行います）

**Comment by NKMR6194** [comment]
:+1:

現在はボタンのロードに時間がかかり、その間に表記が崩れたりしています。その問題も解消できるとbetterだと思います。よろしくお願いします :smile:

**Comment by raryosu** [comment]
記事下のSNSボタンについても同様に吹き出しをすべてなくす形で統一します。

**Comment by NKMR6194** [comment]
:ok_hand:

**Comment by raryosu** [comment]
https://github.com/NKMR6194/proconist.net/commit/97e00924dd4bf589f952783f0af20f4117b0a342 までに大まかな修正を行いました。

ただ，記事下のSNSボタンがいまいちしっくりきません。
1. タイトルの直下に持ってくる
2. 筆者紹介の下に持っていく
3. (位置はそのままで)なんか別のデザインを考える
4. なくす 
という4つの選択肢が頭の中にあります。僕としては4はないにせよ，あとはいずれでも問題ないかなぁと思っています。
もちろん，このままでも良ければこのままでPullReqest発行します。よろしくお願いします。

**Comment by NKMR6194** [comment]
記事下のボタンは、強いて言うなら右詰めになっていることが若干違和感がありますがどうなんだろう

それよりも、ヘッダ脇のボタンが違和感大きい気がします。ボタンのサイズそのもの大きくして、よくあるサイズとの違いを出すといいかもしれないです。　公式のだと、大きめのボタンって対応してますか？

**Comment by raryosu** [comment]
どこにおいても違和感があるので、もしかしたら記事下については、それぞれのボタンの感覚を開ける or 自作のボタンに置き換えたほうがいいのかもしれません。

ヘッダ脇についてですが、縦にでかいボタンはなさそうです。ただ、あの横に長いやつを全体的に大きくしたやつならありそう…
https://about.twitter.com/ja/resources/buttons#tweet
ここのボタンを自作のに置き換えると、「Proconist.net公式のTwitterアカウントへのリンク」という誤解を呼びそうだなぁという気もしています。

**Comment by NKMR6194** [comment]
自作ボタンにする場合は、OSTとかHonokaみたいに動作の文字も入れてやると誤解はなさそう

![2015-10-26 13 03 41](https://cloud.githubusercontent.com/assets/4254002/10721117/201b133a-7be2-11e5-86ea-6bf404f9a282.png)

**Comment by raryosu** [comment]
それもそうですね

では記事下もヘッダ横もこんな感じで自作ボタンに置き換えようと思います。

**Comment by NKMR6194** [comment]
:ok_hand:

**Comment by raryosu** [comment]
修正が大変遅くなり申し訳ありません
さしあたってデザインのみ修正をしています。（リンクのURLは後ほどつけます⇒記事下のほうは多少厄介？）
確認よろしくお願いします。

**Comment by NKMR6194** [comment]
デザインとても良い :+1: :+1: :+1: 
`target="_blank"`にすればボタンをクリックしても別タブで開けて良いと思うけど、どうだろう？
あと、下部に書いてあったTwitterのjsを残しておくとツイート画面がプップアップされるということを発見したけど、どっちがいいかな？

記事下のURL指定はサーバーサイドでHTML生成時に適宜やるのが良い気がします。

**Comment by raryosu** [comment]
👐👐👐
Twitterに関してはJSを残しておきましょう（多分ポップアップするほうが望ましいので）。
ただ，JS無効にしている状態で閲覧された場合（稀な気はしますが）ポップアップもされないので， `target="_blank"` を指定しておくということにしようと思います（JS削ったほうがいいですかね？）

では記事下のは，お任せします。よろしくお願いします。
